version: "3.8"

volumes:
  pleroma-db-data:
  pleroma-uploads:

networks:
  pleroma-net:
    driver: overlay

services:
  pleroma-db:
    env_file:
      - .env
    image: circleci/postgres:9-bullseye-ram
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pleroma-db-data:/var/lib/postgresql/data
      - ${VOLUME_MAIN_DATA_PATH}/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    networks:
      - pleroma-net
    deploy:
      placement:
        constraints:
          - node.role == worker


  pleroma:
    image: pandentia/pleroma:latest
    env_file:
      - pleroma.env
    volumes:
      - ${CONFIG_PATH}/config.exs:/pleroma/config/config.exs:ro
      - ${CONFIG_PATH}/prod.secret.exs:/pleroma/config/prod.secret.exs:ro
      - ${STATIC_PATH}/background1.jpg:/pleroma/static/static/background1.jpg:ro
      - ${STATIC_PATH}/favicon.png:/pleroma/static/static/favicon.png:ro
      - pleroma-uploads:/pleroma/uploads
    depends_on:
      - pleroma-db  
    networks:
      - pleroma-net
    deploy:
      placement:
        constraints:
          - node.role == worker

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8876:80"   # HTTP
      - "7765:443"  # HTTPS
    networks:
      - pleroma-net
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
