services:
  pleroma:
    image: pandentia/pleroma:latest
    container_name: "pleroma"
    hostname: "pleroma"
    restart: always
    depends_on:
      - pleroma-db
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./config.exs:/var/lib/pleroma/config.exs
      - ./prod.secrets.exs:/var/lib/pleroma/config/prod.secrets.exs
      - ./static:/var/lib/pleroma/static
      - pleroma-uploads:/var/lib/pleroma/uploads
    environment:
      DB_USER: pleroma
      DB_PASS: awkward
      DB_HOST: pleroma-db
      DB_NAME: pleroma
      INSTANCE_NAME: Dutchman
      ADMIN_EMAIL: pleroma+admin@example.com
      NOTIFY_EMAIL: pleroma+admin@example.com
      DOMAIN: social.mpampis.com
      PORT: 4000

  pleroma-db:
    image: circleci/postgres:9-bullseye-ram
    container_name: "pleroma-db"
    hostname: "pleroma-db"
    restart: always
    # ports:
    #   - "127.0.0.1:5432:5432"
    volumes:
      - pleroma-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: awkward

volumes:
  pleroma-db-data:
  pleroma-uploads:
