services:
  pleroma:
    image: pandentia/pleroma:latest
    container_name: "pleroma"
    hostname: "pleroma"
    restart: always
    depends_on:
      - pleroma-db
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./config.exs:/pleroma/config.exs
      - ./prod.secret.exs:/pleroma/config/prod.secret.exs
      - ./static:/var/lib/pleroma/static
      - pleroma-uploads:/var/lib/pleroma/uploads
    env_file:
      - pleroma.env


  pleroma-db:
    image: circleci/postgres:9-bullseye-ram
    container_name: "pleroma-db"
    hostname: "pleroma-db"
    restart: always
    # ports:
    #   - "127.0.0.1:5432:5432"
    volumes:
      - pleroma-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: awkward

volumes:
  pleroma-db-data:
  pleroma-uploads:
